version: '3'

services:
  db:
    container_name: DB_NETFLIX
    image: mongo:6.0
    command: --replSet rs0
    volumes:
      - ./db_netflix:/data/db
    ports:
     - 27017:27017
     - 28017:28017
    restart: always